### PR TITLE
Remove numpy type aliases

### PR DESCRIPTION
**Pull request by dsm-72**
See [issue](https://github.com/theislab/diffxpy/issues/224) #224

### CODE REVIEW

**Comment by dsm-72** [comment]
@davidsebfischer @Hoeze please help push this through thanks :)

**Comment by Hoeze** [comment]
Hi @dsm-72, thanks for your PR!
Unfortunately I dont have any merge permissions any more as it seems :sweat_smile: 
Maybe @davidsebfischer can take that over :smile:

**Review by davidsebfischer — APPROVED** [review]

**Comment by davidsebfischer** [comment]
Thank you, @dsm-72!

**Comment by dsm-72** [comment]
@davidsebfischer can we actually release this? otherwise people have to install this via `pip install git+https://github.com/theislab/diffxpy`

**Comment by dsm-72** [comment]
@Hoeze @davidsebfischer bump on this

**Comment by ngvananh2508** [comment]
It still appears this error now. And when I try to downgrade python, batchglm require the version of numpy that has this deprecation. So I can not do anything :3

**Comment by dsm-72** [comment]
Hey David,
I hope this finds you well.
I noticed that commit #225 <https://github.com/theislab/diffxpy/commit/7609ea935936e3739fc4c71b75c8ee8ca57f51ea#diff-996a76c508735f7b227ad35fb08c914e2ee3feace489a13b7ec7de2d04d6fbb0> has the following:
Co-authored-by: Solstice Cerasus ***@***.*** ***@***.***>>

I don’t know how that got there. I think the work computer had the config messed up. In any case, would it be possible for you to purge this from the git history please.
Thank you.

**Comment by dsm-72** [comment]
Just wanted to follow up on this

**Pull request merged**
